name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Zip dist directory
      run: zip -r my-app.zip dist

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: my-app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: https://example.com

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-app

    - name: Unzip artifact
      run: unzip my-app.zip -d my-app

    - name: Deploy to test environment
      run: |
        # For example, deploying to a test server
        echo "Deploying to test environment"

    - name: Clean up artifact
      run: |
        rm -rf my-app my-app.zip

  create_release:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_TEST }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false

  notify:
    needs: [build, deploy, create_release]
    runs-on: ubuntu-latest

    steps:
    - name: Send email notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "CI/CD Pipeline Failed"
        body: "The CI/CD pipeline failed for the project. Please check the GitHub Actions logs for more details."
        to: ${{ secrets.DEVELOPER_EMAIL }}
