name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: https://example.com

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-app

    - name: Deploy to test environment
      run: |
        # Assuming the artifact is a zip file
          unzip my-app.zip -d my-app
          echo "Deploying to test environment"
        # For example, deploying to a test server
        echo "Deploying to test environment"

    - name: Clean up artifact
      run: |
        rm -rf my-app my-app.zip

  notify:
    needs: [build, deploy]
    runs-on: ubuntu-latest

    steps:
    - name: Send email notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "CI/CD Pipeline Failed"
        body: "The CI/CD pipeline failed for the project. Please check the GitHub Actions logs for more details."
        to: ${{ secrets.DEVELOPER_EMAIL }}
